### ISSUE TITLE
Cryptic success message when changing settings

### ISSUE THREAD

**Issue by thielanja** [iLUB/ILIAS-Etherpad-Lite-Plugin#1]
**Describe the bug**
When changing any setting in the live voting (e.g. online or offline, chat on or off), a cryptic success message appears rather than text in a "normal" language.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xpdl_2577287.html
2. Click on Settings
3. change any setting
4. See message

**Expected behavior**
In both cases it should say "Änderungen gespeichert" or "Modifications saved."

**Screenshots**
<img width="316" alt="Bildschirmfoto 2023-11-27 um 14 48 56" src="https://github.com/ilub-unibe-ch/ILIAS-Etherpad-Lite-Plugin/assets/112550466/0d3cdf64-edfd-485b-9a4a-d6276bcf05f7">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
gefixt mit diesem Commit https://github.com/ilub-unibe-ch/ILIAS-Etherpad-Lite-Plugin/commit/6fea20cea57f8e9b97010c4b47dc82d6693931f6
Jetzt steht da 
Änderungen gespeichert
