### ISSUE TITLE
Aktuell kein Zugriff/"Loading" auf Etherpad, wenn Zugriff mit Chrome, Edge...

### ISSUE THREAD

**Issue by samuelinniger** [iLUB/ILIAS-Etherpad-Lite-Plugin#4]
**Describe the bug**
Siehe Bsp: https://ilias.unibe.ch/goto_ilias3_unibe_xpdl_3024427.html

Aktuell kann mit verschiedenen Browsern nicht auf Etherpads zugegriffen werden.
Funktioniert nicht auf Edge, Chrome, Opera. 
(auf Firefox und Safari funktioniert der Zugriff noch).

Gemeldet in den Tickets: ID0145987, ID0145908

**Comment by okaufman** [comment]
Es funktioniert jetzt wieder mit Chrome und Edge. Das Problem lag an der CSP(Content-Security-Policy) 
Ist etwas komisch, da wir diese Policy ca vor eonem Monat angepasst haben. Es könnte aber sein, dass durch ein Browser-Update plötzlich die Ansprüche an die CSP bei den unterschiedlichen Browsern gestiegen sind. 
Ich lasse das Ticket noch offen, damit ich dem am Montag noch weiter nachgehen kann.
